include (arm-none-eabi-gcc)


SET(CMAKE_CROSSCOMPILING TRUE) 
# the name of the target operating system
SET(CMAKE_SYSTEM_NAME Generic)

ENABLE_LANGUAGE(ASM)


SET(SAVE_CMAKE_C_FLAGS_DEBUG 		${CMAKE_C_FLAGS_DEBUG})
SET(SAVE_CMAKE_CXX_FLAGS_DEBUG 		${CMAKE_CXX_FLAGS_DEBUG})
SET(SAVE_CMAKE_ASM_FLAGS_DEBUG 		${CMAKE_ASM_FLAGS_DEBUG})

SET(SAVE_CMAKE_C_FLAGS_RELEASE 		${CMAKE_C_FLAGS_RELEASE})
SET(SAVE_CMAKE_CXX_FLAGS_RELEASE 	${CMAKE_CXX_FLAGS_RELEASE})
SET(SAVE_CMAKE_ASM_FLAGS_RELEASE 	${CMAKE_ASM_FLAGS_RELEASE})

set( CMAKE_C_FLAGS_DEBUG			"")
set( CMAKE_CXX_FLAGS_DEBUG			"")
set( CMAKE_ASM_FLAGS_DEBUG			"")
set( CMAKE_C_FLAGS_RELEASE			"")
set( CMAKE_CXX_FLAGS_RELEASE		"")
set( CMAKE_ASM_FLAGS_RELEASE		"")


include(copy_hal_files_helper)

include (add_executable_hook)

