list(APPEND ARDUINO_FRONTEND_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_gpio.cpp)
list(APPEND ARDUINO_FRONTEND_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_clock.cpp)
list(APPEND ARDUINO_FRONTEND_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_spi.cpp)
list(APPEND ARDUINO_FRONTEND_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_wire.cpp)
list(APPEND ARDUINO_FRONTEND_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_serial.cpp)
list(APPEND ARDUINO_FRONTEND_SOURCES ${CMAKE_CURRENT_LIST_DIR}/frontend_arduino.cpp)
build_library(frontend_arduino ${ARDUINO_FRONTEND_SOURCES})
target_include_directories(frontend_arduino PUBLIC ${CMAKE_CURRENT_LIST_DIR}/)
target_link_libraries(frontend_arduino pinout)
