list(APPEND PROJECT_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_gpio.cpp)
list(APPEND PROJECT_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_clock.cpp)
list(APPEND PROJECT_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_spi.cpp)
list(APPEND PROJECT_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_wire.cpp)
list(APPEND PROJECT_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arduino_serial.cpp)
list(APPEND PROJECT_SOURCES ${CMAKE_CURRENT_LIST_DIR}/frontend_arduino.cpp)
include_directories(${CMAKE_CURRENT_LIST_DIR}/)

